apiVersion: v1
kind: Pod
metadata:
  name: ngc-pod
  labels:
    app: ngc-pod
  namespace: default
spec:
  containers:
    - name: ngc-pod
      image: 'nvcr.io/nvidia/tensorflow:21.09-tf2-py3'
      ports:
        - name: jupyter
          containerPort: 8888
          protocol: TCP
        - containerPort: 22
        - containerPort: 80
      command: ["/bin/bash", "-c"]
      args:
        - . /etc/environment;
          . /etc/profile; 
          apt update -y;
          service ssh start; 
          service xinetd start; 
          echo "root:Fpg@27122211" | chpasswd;
          jupyter notebook --notebook-dir=~ --allow-root &> /dev/null &
          tail -f /dev/null; 
