apiVersion: v1
kind: Pod
metadata:
  name: ngc-pod
  labels:
    app: ngc-pod
  namespace: openshift-gitops
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: ngc-pod
      image: 'docker pull jupyter/tensorflow-notebook:tensorflow-2.6.0'
      ports:
        - name: jupyter
          containerPort: 8888
          protocol: TCP
        - containerPort: 22
        - containerPort: 80
      command: ["/bin/bash", "-c"]
      args:
        - sleep 3000;
