apiVersion: v1
kind: Service
metadata:
  name: ngc-pod
  namespace: openshift-gitops
spec:
  type: ClusterIP
  selector:
    app: ngc-pod
  ports:
    - name: jupyter
      protocol: TCP
      port: 80
      targetPort: 8888
    - name: ssh
      protocol: TCP
      port: 88
      targetPort: 22
