apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngc-pod
  labels:
    app: ngc-pod
  namespace: openshift-gitops
spec:
  selector:
    matchLabels:
      app: ngc-pod
  replicas: 2
  template:
    metadata:
      labels:
         app: ngc-pod
    spec:
      containers:
        - name: ngc-pod
          image: 'denkay123/dk:tensorflow-19.10-py3'
          ports:
            - name: jupyter
              containerPort: 8888
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
            - containerPort: 80
          env:
            - name: JUPYTER_DATA_DIR
              value: "/tmp/.local"
          command: ["/bin/bash", "-c"]
          args:
            - jupyter notebook  --notebook-dir=/tmp --NotebookApp.token='' --NotebookApp.password='' ;
