build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile
        - fpg-dockerfile/**/*.txt
  script:
    - mkdir -p /kaniko/.docker
    - echo "10.92.30.110   example-registry-quay-quay-test.apps.ocp4.nh.com" >> /etc/hosts
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/fpg-dockerfile"
      --dockerfile "Dockerfile"
      --destination "example-registry-quay-quay-test.apps.ocp4.nh.com/sti/fpg:ubuntu-20.04-v1"
      --insecure 
      --skip-tls-verify
      --push-retry 2

